// src/screens/jobs/post/hooks/usePostJob.js
import { useState } from 'react';
import { useAuth } from '../../../../hooks/useAuth';
import { supabase } from '../../../../utils/supabaseClient';
import { Alert } from 'react-native';
import { useNavigation } from '@react-navigation/native';

export const JOB_CATEGORIES = [
  'General Work', 'Gardening', 'Washing', 'Cleaning', 'Domestic',
  'Painting', 'Cabling', 'Construction', 'Tiling', 'Heavy Lifting', 'Other'
];

export const usePostJob = () => {
  const { user } = useAuth();
  const navigation = useNavigation();
  
  const [formData, setFormData] = useState({
    category: '',
    description: '',
    location_city: '',
    location_suburb: '',
    scheduled_date: '',
    start_time: '',
    end_time: '',
    duration_hours: '',
    budget: '',
  });

  const [errors, setErrors] = useState({});
  const [showConfirmation, setShowConfirmation] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const updateField = (field, value) => {
    setFormData(prev => ({ ...prev, [field]: value }));
    if (errors[field]) {
      setErrors(prev => ({ ...prev, [field]: '' }));
    }
  };

  const updateTimeField = (field, value) => {
    setFormData(prev => {
      const newData = { ...prev, [field]: value };
      
      if (newData.start_time && newData.end_time) {
        const start = new Date(`2000-01-01 ${newData.start_time}`);
        const end = new Date(`2000-01-01 ${newData.end_time}`);
        const diffMs = end - start;
        const hours = (diffMs / (1000 * 60 * 60)).toFixed(1);
        newData.duration_hours = hours > 0 ? hours : '';
      }
      
      return newData;
    });

    if (errors[field]) {
      setErrors(prev => ({ ...prev, [field]: '' }));
    }
  };

  const validateForm = () => {
    const newErrors = {};
    
    if (!formData.category) newErrors.category = 'Please select a category';
    if (!formData.description?.trim()) newErrors.description = 'Please enter a description';
    if (!formData.location_city) newErrors.location_city = 'Please select a city';
    if (!formData.location_suburb?.trim()) newErrors.location_suburb = 'Please enter a suburb';
    if (!formData.scheduled_date) newErrors.scheduled_date = 'Please select a date';
    if (!formData.start_time) newErrors.start_time = 'Please select start time';
    if (!formData.end_time) newErrors.end_time = 'Please select end time';
    if (!formData.budget) newErrors.budget = 'Please enter a budget';

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSaveDraft = () => {
    return validateForm();
  };

  // TYPE A API CALL - Immediate submission
  const handleFinalSubmit = async () => {
  if (isSubmitting) return;
  
  setIsSubmitting(true);
  
  try {
    if (!user) {
      Alert.alert('Error', 'You must be logged in to post jobs');
      return;
    }

    console.log('👤 User ID:', user.id);

    const jobData = {
      employer_id: user.id,
      // NO title field - using category + description only
      description: formData.description,
      category: formData.category,
      location_city: formData.location_city,
      location_suburb: formData.location_suburb,
      scheduled_date: formData.scheduled_date,
      time_from: formData.start_time,
      time_to: formData.end_time,
      duration_hours: parseFloat(formData.duration_hours) || 0,
      budget: parseFloat(formData.budget) || 0,
      budget_currency: 'ZAR',
      status: 'open',
      applicant_count: 0,
      // job_reference will be auto-generated by the database trigger
    };

    console.log('📤 Submitting job:', jobData);

    const { data, error } = await supabase
      .from('jobs')
      .insert([jobData])
      .select()
      .single();

    if (error) {
      console.error('❌ Supabase error:', error);
      throw error;
    }

    console.log('✅ Job posted successfully! ID:', data.id, 'Reference:', data.job_reference);
    
    // Reset form
    setFormData({
      category: '',
      description: '',
      location_city: '',
      location_suburb: '',
      scheduled_date: '',
      start_time: '',
      end_time: '',
      duration_hours: '',
      budget: '',
    });
    
    setShowConfirmation(false);
    
    Alert.alert(
      'Success!', 
      `Job posted successfully!\nReference: ${data.job_reference}`
    );
    
  } catch (error) {
    console.error('💥 Job posting error:', error);
    Alert.alert(
      'Posting Failed', 
      error.message || 'Could not post your job. Please try again.'
    );
  } finally {
    setIsSubmitting(false);
  }
};

  return {
    formData,
    updateField,
    updateTimeField,
    errors,
    showConfirmation,
    setShowConfirmation,
    isSubmitting,
    handleSaveDraft,
    handleFinalSubmit,
    categories: JOB_CATEGORIES
  };
};